"""
Question bank for the YoungMinds Skill Test portal.

Each domain has exactly 15 MCQs. Each question is a tuple:
    (question_text, [option1, option2, option3, option4], index_of_correct_option)

Option order is shuffled once when the database is seeded, so the
correct answer is not always in the same position.
"""

DOMAINS = [
    # ------------------------------------------------------------------ CSE
    {
        "slug": "ai-ml",
        "name": "Artificial Intelligence & Machine Learning",
        "short": "AI / ML",
        "branch": "CSE",
        "description": "Supervised and unsupervised learning, neural networks, evaluation metrics.",
        "questions": [
            ("Which of the following is a supervised learning algorithm?",
             ["K-Means", "Linear Regression", "Apriori", "PCA"], 1),
            ("What does overfitting mean?",
             ["The model performs well on training data but poorly on unseen data",
              "The model performs poorly on both training and test data",
              "The model is too simple to learn patterns",
              "The model trains too quickly"], 0),
            ("Which activation function outputs values between 0 and 1?",
             ["ReLU", "Sigmoid", "Tanh", "Leaky ReLU"], 1),
            ("Which technique is commonly used to reduce overfitting in neural networks?",
             ["Dropout", "Training for unlimited epochs", "Removing the validation set", "Using only a larger learning rate"], 0),
            ("In KNN, what does 'K' refer to?",
             ["Number of clusters", "Number of nearest neighbours considered", "Number of features", "Number of hidden layers"], 1),
            ("Which metric is more suitable than accuracy for an imbalanced classification dataset?",
             ["F1-score", "Mean Squared Error", "R-squared", "Mean Absolute Error"], 0),
            ("Gradient descent is used to:",
             ["Minimize the loss function", "Increase the dataset size", "Normalize the input data", "Split data into train and test"], 0),
            ("Convolutional Neural Networks (CNNs) are mainly used for:",
             ["Image data", "Database queries", "Spreadsheet formulas", "Audio file compression"], 0),
            ("Which of the following is an unsupervised learning technique?",
             ["Logistic Regression", "Decision Tree", "K-Means Clustering", "Support Vector Machine"], 2),
            ("What is the main purpose of a train-test split?",
             ["To increase the amount of data", "To evaluate the model on unseen data",
              "To reduce the number of features", "To speed up training"], 1),
            ("Which library is primarily used for building deep learning models?",
             ["Pandas", "TensorFlow", "Matplotlib", "BeautifulSoup"], 1),
            ("What does RNN stand for?",
             ["Random Neural Network", "Recurrent Neural Network", "Recursive Node Network", "Regional Neural Network"], 1),
            ("Precision is calculated as:",
             ["TP / (TP + FP)", "TP / (TP + FN)", "TN / (TN + FP)", "(TP + TN) / Total"], 0),
            ("Which algorithm is used in reinforcement learning?",
             ["Q-Learning", "K-Means", "Naive Bayes", "Apriori"], 0),
            ("A model with high bias usually leads to:",
             ["Overfitting", "Underfitting", "Data leakage", "A perfect fit"], 1),
        ],
    },
    {
        "slug": "data-science",
        "name": "Data Science",
        "short": "Data Science",
        "branch": "CSE",
        "description": "Statistics, data preparation, feature engineering and model validation.",
        "questions": [
            ("Which Python library provides the DataFrame structure for data manipulation?",
             ["NumPy", "Pandas", "Seaborn", "Flask"], 1),
            ("Which measure of central tendency is least affected by outliers?",
             ["Mean", "Median", "Range", "Variance"], 1),
            ("Which plot is best for showing the distribution of a single numeric variable?",
             ["Pie chart", "Histogram", "Line chart", "Scatter plot"], 1),
            ("Which Pandas function fills missing values?",
             ["dropna()", "fillna()", "isnull()", "merge()"], 1),
            ("What is the range of the Pearson correlation coefficient?",
             ["0 to 1", "-1 to 1", "0 to 100", "-100 to 100"], 1),
            ("Feature scaling means:",
             ["Removing unwanted features", "Bringing features to a similar range of values",
              "Adding new rows to the dataset", "Encoding target labels"], 1),
            ("Which technique converts a categorical variable into separate binary columns?",
             ["Label smoothing", "One-hot encoding", "Normalization", "Binning"], 1),
            ("A p-value below 0.05 typically means:",
             ["We fail to reject the null hypothesis", "We reject the null hypothesis",
              "The data is normally distributed", "The sample size is too small"], 1),
            ("Which of these is a dimensionality reduction technique?",
             ["PCA", "KNN", "Random Forest", "Linear Regression"], 0),
            ("Standard deviation measures:",
             ["The central value of data", "The spread of data around the mean",
              "The most frequent value", "The number of records"], 1),
            ("In the CRISP-DM process, which phase comes first?",
             ["Modeling", "Business Understanding", "Deployment", "Evaluation"], 1),
            ("Which SQL clause filters results after GROUP BY?",
             ["WHERE", "HAVING", "ORDER BY", "LIMIT"], 1),
            ("Which NumPy function creates an array filled with zeros?",
             ["np.zeros()", "np.null()", "np.clear()", "np.blank()"], 0),
            ("Cross-validation is mainly used to:",
             ["Clean the dataset", "Assess how well a model generalizes",
              "Visualize the data", "Store data efficiently"], 1),
            ("In a box plot, the box represents:",
             ["Mean plus or minus one standard deviation", "The interquartile range (Q1 to Q3)",
              "The minimum to maximum values", "Only the median"], 1),
        ],
    },
    {
        "slug": "computer-science",
        "name": "Computer Science Fundamentals",
        "short": "Computer Science",
        "branch": "CSE",
        "description": "Data structures, algorithms, operating systems, DBMS and networks.",
        "questions": [
            ("What is the time complexity of binary search on a sorted array?",
             ["O(n)", "O(log n)", "O(n log n)", "O(1)"], 1),
            ("Which data structure follows LIFO (Last In, First Out)?",
             ["Queue", "Stack", "Linked List", "Tree"], 1),
            ("Which of the following is NOT an operating system?",
             ["Linux", "Windows", "MySQL", "macOS"], 2),
            ("Which layer of the OSI model is responsible for routing?",
             ["Transport layer", "Network layer", "Data Link layer", "Session layer"], 1),
            ("A primary key in a database table:",
             ["Can contain NULL values", "Uniquely identifies each record",
              "Can contain duplicate values", "Must always be a foreign key"], 1),
            ("Which of the following is NOT one of the necessary conditions for deadlock?",
             ["Mutual exclusion", "Hold and wait", "Preemption", "Circular wait"], 2),
            ("Which sorting algorithm has a worst-case time complexity of O(n log n)?",
             ["Quick Sort", "Merge Sort", "Bubble Sort", "Insertion Sort"], 1),
            ("Normalization in DBMS is used to:",
             ["Increase data redundancy", "Reduce data redundancy", "Encrypt data", "Back up data"], 1),
            ("Which traversal of a Binary Search Tree gives the elements in sorted order?",
             ["Preorder", "Inorder", "Postorder", "Level order"], 1),
            ("TCP is a:",
             ["Connectionless protocol", "Connection-oriented protocol",
              "Physical layer protocol", "Programming language"], 1),
            ("Method overloading is an example of:",
             ["Polymorphism", "Encapsulation", "Abstraction", "Inheritance"], 0),
            ("Virtual memory allows:",
             ["The CPU to run faster", "Execution of processes larger than physical memory",
              "More cache memory", "Formatting of the hard disk"], 1),
            ("Which algorithm finds the shortest path from a single source in a graph with non-negative weights?",
             ["Kruskal's algorithm", "Dijkstra's algorithm", "Prim's algorithm", "Depth First Search"], 1),
            ("What is the default port number for HTTP?",
             ["21", "80", "443", "25"], 1),
            ("A compiler:",
             ["Translates the whole high-level program into machine code before execution",
              "Executes the program line by line at runtime",
              "Converts machine code into a high-level language",
              "Only works with assembly language"], 0),
        ],
    },
    {
        "slug": "python-full-stack",
        "name": "Python Full Stack Development",
        "short": "Python Full Stack",
        "branch": "CSE",
        "description": "Python, Django and Flask, REST APIs, HTML, CSS and JavaScript.",
        "questions": [
            ("Which of the following is a Python web framework?",
             ["React", "Django", "Angular", "Spring"], 1),
            ("What is the output of print(type([])) in Python?",
             ["<class 'list'>", "<class 'tuple'>", "<class 'dict'>", "<class 'set'>"], 0),
            ("Which HTTP method is typically used to create a new resource in a REST API?",
             ["GET", "POST", "DELETE", "HEAD"], 1),
            ("In Flask, which decorator maps a URL to a view function?",
             ["@app.url", "@app.route", "@app.path", "@app.map"], 1),
            ("Which HTML tag creates a hyperlink?",
             ["<link>", "<a>", "<href>", "<url>"], 1),
            ("Which CSS property changes the text color?",
             ["font-color", "color", "text-color", "fg-color"], 1),
            ("Which Django command applies database migrations?",
             ["python manage.py migrate", "python manage.py runserver",
              "python manage.py startapp", "python manage.py shell"], 0),
            ("Which JavaScript method converts a JSON string into an object?",
             ["JSON.stringify()", "JSON.parse()", "JSON.object()", "JSON.convert()"], 1),
            ("Which keyword is used to define a function in Python?",
             ["function", "def", "fun", "define"], 1),
            ("Which of these Python data types is immutable?",
             ["list", "dict", "tuple", "set"], 2),
            ("What does pip do?",
             ["Runs Python files", "Installs Python packages", "Compiles Python code", "Debugs Python code"], 1),
            ("HTTP status code 404 means:",
             ["Internal server error", "Resource not found", "Unauthorized", "Request successful"], 1),
            ("In Jinja2 templates, which syntax outputs a variable?",
             ["{% var %}", "{{ var }}", "<%= var %>", "${var}"], 1),
            ("Which JavaScript feature is used to make asynchronous HTTP requests?",
             ["fetch()", "alert()", "console.log()", "document.write()"], 0),
            ("A Python virtual environment is used to:",
             ["Speed up program execution", "Isolate project dependencies",
              "Encrypt project files", "Host websites online"], 1),
        ],
    },
    {
        "slug": "java-full-stack",
        "name": "Java Full Stack Development",
        "short": "Java Full Stack",
        "branch": "CSE",
        "description": "Core Java, Spring Boot, JPA and Hibernate, JDBC and build tools.",
        "questions": [
            ("Which is the correct entry-point method signature in Java?",
             ["public static void main(String[] args)", "void start()", "public main()", "static run()"], 0),
            ("Which of the following is a Java backend framework?",
             ["Spring Boot", "Flask", "Laravel", "Express"], 0),
            ("What does JVM stand for?",
             ["Java Virtual Machine", "Java Variable Method", "Java Visual Model", "Joint Virtual Machine"], 0),
            ("Which keyword is used to inherit a class in Java?",
             ["implements", "extends", "inherits", "super"], 1),
            ("Which collection does NOT allow duplicate elements?",
             ["ArrayList", "HashSet", "LinkedList", "Vector"], 1),
            ("Which annotation marks a class as a REST controller in Spring?",
             ["@Service", "@RestController", "@Entity", "@Repository"], 1),
            ("JDBC is used for:",
             ["Designing GUIs", "Connecting Java applications to databases", "Unit testing", "Version control"], 1),
            ("Which of the following is NOT a primitive data type in Java?",
             ["int", "boolean", "String", "char"], 2),
            ("Hibernate is a:",
             ["Frontend framework", "ORM (Object Relational Mapping) framework", "Build tool", "Web server"], 1),
            ("Maven is primarily used for:",
             ["Build automation and dependency management", "Storing data",
              "UI testing", "Version control"], 0),
            ("Which keywords are used for exception handling in Java?",
             ["try", "catch", "finally", "All of these"], 3),
            ("Which of these is a frontend JavaScript library commonly paired with a Spring Boot backend?",
             ["React", "Hibernate", "JUnit", "Tomcat"], 0),
            ("Which access modifier provides the widest accessibility?",
             ["private", "protected", "default (package-private)", "public"], 3),
            ("Which JPA annotation marks a field as the primary key?",
             ["@Id", "@Key", "@Primary", "@Column"], 0),
            ("What is the default port of the embedded Tomcat server in Spring Boot?",
             ["8000", "8080", "3000", "5000"], 1),
        ],
    },
    {
        "slug": "data-analysis",
        "name": "Data Analysis",
        "short": "Data Analysis",
        "branch": "CSE",
        "description": "Excel, SQL, Power BI, Tableau and descriptive statistics.",
        "questions": [
            ("Which Excel function calculates the average of a range?",
             ["SUM()", "AVERAGE()", "COUNT()", "MAX()"], 1),
            ("VLOOKUP in Excel is used to:",
             ["Sort data", "Look up a value in the first column of a table and return a value from the same row",
              "Create charts", "Protect worksheets"], 1),
            ("Power BI is a:",
             ["Programming language", "Business intelligence and data visualization tool",
              "Relational database", "Operating system"], 1),
            ("Which SQL statement is used to retrieve data from a table?",
             ["GET", "SELECT", "FETCH ALL", "RETRIEVE"], 1),
            ("A pivot table is used for:",
             ["Summarizing and aggregating data", "Writing macros", "Drawing shapes", "Sending emails"], 0),
            ("Which chart type is best for showing a trend over time?",
             ["Pie chart", "Line chart", "Donut chart", "Treemap"], 1),
            ("Data cleaning includes:",
             ["Handling missing values and removing duplicates", "Only creating charts",
              "Presenting final reports", "Purchasing new datasets"], 0),
            ("The mode of a dataset is:",
             ["The middle value", "The most frequent value", "The average value", "The difference between max and min"], 1),
            ("Which SQL function returns the number of rows?",
             ["SUM()", "COUNT()", "TOTAL()", "NUM()"], 1),
            ("Tableau is mainly used for:",
             ["Data visualization", "Web hosting", "Compiling code", "Network configuration"], 0),
            ("What does KPI stand for?",
             ["Key Performance Indicator", "Key Process Input", "Known Performance Index", "Key Product Item"], 0),
            ("Which JOIN returns only the rows that have matching values in both tables?",
             ["LEFT JOIN", "INNER JOIN", "FULL OUTER JOIN", "CROSS JOIN"], 1),
            ("Which Pandas method gives summary statistics of numeric columns?",
             ["df.info()", "df.describe()", "df.head()", "df.shape"], 1),
            ("DAX (Data Analysis Expressions) is the formula language of:",
             ["Power BI", "MySQL", "Photoshop", "Git"], 0),
            ("An outlier is:",
             ["A value that lies far away from other observations", "The mean of the data",
              "A missing value", "A duplicated row"], 0),
        ],
    },
    {
        "slug": "mern-stack",
        "name": "MERN Stack Development",
        "short": "MERN Stack",
        "branch": "CSE",
        "description": "MongoDB, Express.js, React and Node.js for full-stack JavaScript apps.",
        "questions": [
            ("What does MERN stand for?",
             ["MongoDB, Express.js, React, Node.js", "MySQL, Express.js, React, Node.js",
              "MongoDB, Ember.js, React, Next.js", "MariaDB, Express.js, Redux, Node.js"], 0),
            ("How does MongoDB store data?",
             ["As rows in tables", "As BSON documents inside collections",
              "Only as key-value pairs", "As XML files"], 1),
            ("Express.js is:",
             ["A NoSQL database", "A minimal web application framework for Node.js",
              "A React state management library", "A CSS framework"], 1),
            ("Which React hook is used to manage state in a functional component?",
             ["useEffect", "useState", "useRef", "useMemo"], 1),
            ("A useEffect hook with an empty dependency array [] runs:",
             ["On every render", "Only once, after the first render", "Never", "Only when the component unmounts"], 1),
            ("Node.js is:",
             ["A web browser", "A JavaScript runtime built on Chrome's V8 engine",
              "A relational database", "A frontend framework"], 1),
            ("Which command creates a package.json file for a new Node.js project?",
             ["npm init", "npm start", "node new", "npm create-db"], 0),
            ("Mongoose is:",
             ["An ODM library for working with MongoDB in Node.js", "A routing library for React",
              "A testing framework", "A CSS preprocessor"], 0),
            ("What are the parameters of a typical Express middleware function?",
             ["(req, res, next)", "(a, b)", "(err)", "(state, action)"], 0),
            ("JSX is:",
             ["A syntax extension that lets you write HTML-like markup inside JavaScript",
              "A database query language", "A Java library", "A JSON parser"], 0),
            ("Props in React are:",
             ["Mutable internal state of a component", "Read-only data passed from a parent to a child component",
              "CSS class names", "Database records"], 1),
            ("Which MongoDB method inserts a single document into a collection?",
             ["insertOne()", "addOne()", "push()", "createRow()"], 0),
            ("JWT (JSON Web Token) is commonly used for:",
             ["Stateless authentication and authorization", "Styling components",
              "Compressing images", "Indexing database fields"], 0),
            ("Why does React need a unique 'key' prop on list items?",
             ["To identify which items changed, were added or removed", "To encrypt the list data",
              "To apply styles to each item", "To fetch data for each item"], 0),
            ("Which built-in Express middleware parses incoming JSON request bodies?",
             ["express.json()", "express.static()", "express.Router()", "express.cookie()"], 0),
        ],
    },
    {
        "slug": "web-development",
        "name": "Web Development",
        "short": "Web Development",
        "branch": "CSE",
        "description": "HTML, CSS, JavaScript, responsive design and web fundamentals.",
        "questions": [
            ("What does HTML stand for?",
             ["HyperText Markup Language", "High Text Machine Language",
              "Hyperlink Text Mark Language", "Home Tool Markup Language"], 0),
            ("Which semantic HTML element is meant for a block of navigation links?",
             ["<nav>", "<div>", "<span>", "<links>"], 0),
            ("What is the order of the CSS box model from the inside out?",
             ["Content, padding, border, margin", "Content, margin, border, padding",
              "Padding, content, border, margin", "Border, padding, content, margin"], 0),
            ("Which CSS layout system is designed for one-dimensional layouts (a row or a column)?",
             ["Flexbox", "CSS Grid", "Tables", "Multi-column layout"], 0),
            ("Which CSS selector has the highest specificity?",
             ["#header (ID selector)", ".header (class selector)", "div (element selector)", "* (universal selector)"], 0),
            ("In JavaScript, a variable declared with 'let' is:",
             ["Block-scoped", "Function-scoped only", "Always global", "Immutable"], 0),
            ("What does the === operator check in JavaScript?",
             ["Both value and type are equal", "Only the value is equal",
              "Assigns a value", "Only the data type"], 0),
            ("CSS media queries are mainly used for:",
             ["Responsive design across screen sizes", "Querying a database",
              "Downloading media files", "Playing videos"], 0),
            ("Which HTTP method is idempotent and typically replaces a resource entirely?",
             ["PUT", "POST", "CONNECT", "OPTIONS"], 0),
            ("What does DOM stand for?",
             ["Document Object Model", "Data Object Management",
              "Digital Output Module", "Document Oriented Markup"], 0),
            ("Which attribute provides alternative text for an image?",
             ["alt", "title", "src", "href"], 0),
            ("Data saved with localStorage in a browser:",
             ["Persists with no expiration until it is cleared", "Is deleted when the tab closes",
              "Is stored on the web server", "Is sent to the server with every request"], 0),
            ("What does CORS stand for?",
             ["Cross-Origin Resource Sharing", "Cross-Object Request System",
              "Central Origin Resource Service", "Cached Origin Request Sharing"], 0),
            ("What is the default port for HTTPS?",
             ["443", "80", "8080", "21"], 0),
            ("Which of the following is a CSS framework?",
             ["Bootstrap", "Django", "Express", "Laravel"], 0),
        ],
    },
    # ------------------------------------------------------------------ ECE
    {
        "slug": "matlab",
        "name": "MATLAB Programming",
        "short": "MATLAB",
        "branch": "ECE",
        "description": "Matrices, scripts, plotting and signal processing functions.",
        "questions": [
            ("What does MATLAB stand for?",
             ["Matrix Laboratory", "Math Laboratory", "Mathematical Language", "Matrix Language Tool"], 0),
            ("Which operator performs element-wise multiplication in MATLAB?",
             ["*", ".*", "x", "**"], 1),
            ("MATLAB array indexing starts at:",
             ["0", "1", "-1", "Any user-defined value"], 1),
            ("Which command removes all variables from the workspace?",
             ["clc", "clear", "close all", "delete"], 1),
            ("Which command clears the Command Window?",
             ["clc", "clear", "cls", "reset"], 0),
            ("Which function creates a 3x3 identity matrix?",
             ["ones(3)", "eye(3)", "zeros(3)", "id(3)"], 1),
            ("Which function draws a 2-D line plot?",
             ["plot()", "draw()", "graph()", "line2d()"], 0),
            ("Which symbol starts a comment in MATLAB?",
             ["//", "#", "%", "--"], 2),
            ("What does linspace(0, 1, 5) generate?",
             ["5 equally spaced points from 0 to 1", "Numbers from 0 to 5 in steps of 1",
              "Numbers from 1 to 5", "5 random numbers"], 0),
            ("What is the effect of a semicolon at the end of a MATLAB statement?",
             ["It ends the program", "It suppresses the output display", "It creates a comment", "It throws an error"], 1),
            ("inv(A) computes:",
             ["The transpose of A", "The inverse of matrix A", "The determinant of A", "The eigenvalues of A"], 1),
            ("Which operator gives the (complex conjugate) transpose of a matrix?",
             ["' (apostrophe)", "^", "~", "T"], 0),
            ("What is the file extension of a MATLAB script or function file?",
             [".mat", ".m", ".ml", ".mlb"], 1),
            ("Which function computes the Fast Fourier Transform?",
             ["fft()", "fourier_t()", "ft()", "dft()"], 0),
            ("size(A) returns:",
             ["Only the number of elements", "The dimensions (rows and columns) of A",
              "The memory used by A", "The data type of A"], 1),
        ],
    },
    {
        "slug": "vlsi",
        "name": "VLSI Design",
        "short": "VLSI",
        "branch": "ECE",
        "description": "CMOS, Verilog HDL, digital design flow, timing and FPGAs.",
        "questions": [
            ("What does VLSI stand for?",
             ["Very Large Scale Integration", "Very Low Signal Integration",
              "Variable Large Scale Interface", "Very Large System Interconnect"], 0),
            ("Which of the following is a Hardware Description Language?",
             ["Verilog", "Python", "HTML", "SQL"], 0),
            ("CMOS technology uses:",
             ["Only NMOS transistors", "Only PMOS transistors", "Both NMOS and PMOS transistors", "Only BJTs"], 2),
            ("The main advantage of CMOS logic is:",
             ["High static power consumption", "Very low static power consumption",
              "Large chip area", "Slow switching"], 1),
            ("A flip-flop is:",
             ["A combinational circuit", "A sequential element that stores one bit",
              "An analog amplifier", "A power supply"], 1),
            ("In Verilog, a module definition ends with which keyword?",
             ["end", "endmodule", "stop", "finish"], 1),
            ("Setup time is the minimum time for which:",
             ["Data must be stable before the active clock edge", "Data must be stable after the active clock edge",
              "The clock stays high", "A signal propagates through a gate"], 0),
            ("What does FPGA stand for?",
             ["Field Programmable Gate Array", "Fixed Programmable Gate Array",
              "Fast Processing Gate Array", "Field Processing Graphic Array"], 0),
            ("Which of the following is a universal gate?",
             ["AND", "OR", "NAND", "XOR"], 2),
            ("Which operator is used for a blocking assignment in Verilog?",
             ["<=", "=", ":=", "=="], 1),
            ("Moore's Law states that the number of transistors on a chip doubles approximately every:",
             ["6 months", "2 years", "5 years", "10 years"], 1),
            ("Which step of the design flow converts RTL code into a gate-level netlist?",
             ["Placement", "Synthesis", "Routing", "Fabrication"], 1),
            ("What does ASIC stand for?",
             ["Application Specific Integrated Circuit", "Advanced System Integrated Circuit",
              "Analog Signal Integrated Circuit", "Automated Silicon Integrated Circuit"], 0),
            ("Dynamic (switching) power in CMOS is proportional to:",
             ["α·C·V²·f", "Only the supply voltage V", "Only the resistance R", "Only the temperature"], 0),
            ("A multiplexer with n select lines can have how many data inputs?",
             ["n", "2n", "2^n", "n²"], 2),
        ],
    },
    {
        "slug": "embedded-systems",
        "name": "Embedded Systems",
        "short": "Embedded",
        "branch": "ECE",
        "description": "Microcontrollers, embedded C, communication protocols and RTOS.",
        "questions": [
            ("A microcontroller integrates:",
             ["CPU, memory and I/O peripherals on a single chip", "Only a CPU", "Only memory", "Only a GPU"], 0),
            ("The Arduino Uno board is based on which microcontroller?",
             ["ATmega328P", "ARM Cortex-A53", "Intel Core i5", "Intel 8085"], 0),
            ("Which communication protocol uses SDA and SCL lines?",
             ["SPI", "I2C", "UART", "CAN"], 1),
            ("UART communication is:",
             ["Synchronous parallel", "Asynchronous serial", "Wireless only", "Optical"], 1),
            ("What does RTOS stand for?",
             ["Real-Time Operating System", "Rapid Transfer Operating System",
              "Remote Terminal Operating System", "Runtime Operating System"], 0),
            ("PWM (Pulse Width Modulation) is commonly used for:",
             ["Controlling motor speed or LED brightness", "Storing data",
              "Connecting to the internet", "Compiling code"], 0),
            ("The purpose of a watchdog timer is to:",
             ["Reset the system if the software hangs", "Measure temperature",
              "Display the current time", "Increase clock speed"], 0),
            ("Which programming language is most widely used in embedded systems?",
             ["C", "HTML", "PHP", "R"], 0),
            ("An ADC converts:",
             ["Digital signals to analog", "Analog signals to digital", "AC to DC", "Serial data to parallel"], 1),
            ("An interrupt is:",
             ["A signal that makes the processor pause and run an Interrupt Service Routine",
              "A power failure", "A compilation error", "A type of memory"], 0),
            ("Standard SPI communication typically uses how many signal lines?",
             ["2", "4", "1", "8"], 1),
            ("EEPROM is:",
             ["Volatile memory", "Non-volatile, electrically erasable memory", "A CPU register", "Cache memory"], 1),
            ("In embedded C, the 'volatile' keyword indicates that a variable:",
             ["May change unexpectedly, for example from an ISR or hardware register",
              "Is a constant", "Is stored in ROM", "Is deleted after use"], 0),
            ("The ARM processor architecture is based on:",
             ["RISC", "CISC", "Quantum computing", "Analog computing"], 0),
            ("Raspberry Pi is best described as a:",
             ["Single-board computer", "Sensor module", "Programming language", "Power regulator"], 0),
        ],
    },
    # ------------------------------------------------------------------ EEE
    {
        "slug": "simulink",
        "name": "Simulink for Electrical Systems",
        "short": "Simulink",
        "branch": "EEE",
        "description": "Block modeling, solvers, control systems and power electronics simulation.",
        "questions": [
            ("Simulink is:",
             ["A block-diagram environment for modeling and simulation in MATLAB",
              "A relational database", "A web framework", "A text editor"], 0),
            ("What is the default file extension of a Simulink model (recent versions)?",
             [".slx", ".m", ".mat", ".sim"], 0),
            ("Which block is used to view signals over time during simulation?",
             ["Scope", "Gain", "Constant", "Mux"], 0),
            ("The Gain block:",
             ["Multiplies the input by a constant value", "Integrates the input",
              "Adds random noise", "Stores data to a file"], 0),
            ("The Integrator block performs:",
             ["Differentiation of the input", "Integration of the input signal",
              "Multiplication of two inputs", "Saturation of the input"], 1),
            ("Simscape Electrical (formerly SimPowerSystems) is used for:",
             ["Modeling electrical and power systems", "Designing websites",
              "Editing images", "Managing databases"], 0),
            ("The Transfer Function block represents:",
             ["A linear system in the Laplace (s) domain", "Only a time delay",
              "A random number generator", "A set of logic gates"], 0),
            ("The Step block generates:",
             ["A sine wave", "A signal that switches from one value to another at a specified time",
              "Random noise", "A continuously increasing ramp"], 1),
            ("Which variable-step solver is the common default for continuous Simulink models?",
             ["ode45", "fft", "lsqr", "gradient"], 0),
            ("The Mux block:",
             ["Combines multiple signals into a single vector signal", "Splits a vector into separate signals",
              "Amplifies a signal", "Filters high frequencies"], 0),
            ("The PID Controller block is used for:",
             ["Closed-loop feedback control", "Data storage", "3-D plotting", "Generating random inputs"], 0),
            ("An inverter model in a power electronics simulation converts DC into:",
             ["DC at a higher voltage", "AC", "Mechanical energy", "Heat"], 1),
            ("The Sum block:",
             ["Adds or subtracts its inputs", "Multiplies its inputs", "Integrates its inputs", "Delays its inputs"], 0),
            ("Which block sends simulation data to the MATLAB workspace?",
             ["To Workspace", "Scope", "Terminator", "Ground"], 0),
            ("In Simscape Electrical Specialized Power Systems, the powergui block is needed to:",
             ["Set the simulation type (continuous, discrete or phasor)", "Plot signals",
              "Generate C code", "Add noise to signals"], 0),
        ],
    },
]

BRANCHES = {
    "CSE": "Computer Science & allied branches",
    "ECE": "Electronics & Communication",
    "EEE": "Electrical & Electronics",
}
